project_id = "jslfqoxxmilfolrwvfaa"

[functions.fetch-crypto-data]
verify_jwt = false

[functions.fetch-taapi-data]
verify_jwt = false

[functions.fetch-forex-data]
verify_jwt = false

[functions.fetch-forex-chart-data]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.send-kyc-notification]
verify_jwt = false

[functions.send-deposit-notification]
verify_jwt = false

[functions.send-withdrawal-notification]
verify_jwt = false

[functions.send-account-notification]
verify_jwt = false
